Practical No.:2
Roll no.:13221

In [1]:
import numpy as np

In [2]:
x= np.array([[3,2,1,0],[7,6,5,4],[11,10,9,8]])

In [3]:
print(x)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [4]:
print("value at [0][0] and [0][1] : ",x[0:1,0:2])

value at [0][0] and [0][1] :  [[3 2]]


In [5]:
print("value at[0][1] , [0][2] , [0][3] :",x[0:1,1:4])

value at[0][1] , [0][2] , [0][3] : [[2 1 0]]


In [6]:
print("value at[1][0] :",x[1:2, 0:1])

value at[1][0] : [[7]]


In [7]:
print("value at[1][1],[1,2],[1,3] :",x[1:2,1:4])

value at[1][1],[1,2],[1,3] : [[6 5 4]]


In [8]:
print(x[1:3,1:4])

[[ 6  5  4]
 [10  9  8]]


In [10]:
y=np.array([[12 ,45 ,33 ,8], [27 ,59 ,41 ,19],[36 ,22 ,54 ,48],[6 ,31 ,17 ,50]])