Assignment No.:1
Roll no.:13221

In [1]:
import numpy as np

In [2]:
x = np.array([2,3,5,7,10])

In [3]:
print(x)

[ 2  3  5  7 10]


In [4]:
type(x)

numpy.ndarray

In [5]:
x = np.array(([2,5,7,10]),dtype="float")

In [6]:
type(x)

numpy.ndarray

In [7]:
x = np.ones((3,4))

In [8]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
x = np.zeros((3,4))

In [10]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
x = np.full((3,4),7)

In [12]:
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [14]:
x = np.eye(3,3)

In [15]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
x = np.arange(2,10,3)

In [17]:
print(x)

[2 5 8]


In [19]:
x = np.linspace(7,10,10)

In [20]:
print(x)

[ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]
